name: OpenPolitics
tagline: An open source plan for the UK. Take control, and create the future you want.

markdown: kramdown

exclude: ["vendor"]

kramdown:
  auto_ids: true

baseurl: /

data_source: data

gems:
  - jemoji
  
defaults:
-
  scope:
    path: "manifesto"
    type: "pages"
  values:
    layout: "policy"
-
  scope:
    path: "manifesto/constituencies"
    type: "pages"
  values:
    layout: "local_policy"
